- Data Pre-processing

In [2]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

data = pd.read_csv("suv_data.csv")

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
from sklearn.preprocessing import OneHotEncoder 

gender_encoder= OneHotEncoder()
gender_encoded=gender_encoder.fit_transform(data[['Gender']]).toarray()

gender_dataframe=pd.DataFrame(data=gender_encoded,columns=gender_encoder.categories_[0])
gender_dataframe

data=pd.concat([data,gender_dataframe],axis=1)
data.drop(columns='Gender',inplace=True)
data

User ID  Age  EstimatedSalary  Purchased  Female  Male
0    15624510   19            19000          0     0.0   1.0
1    15810944   35            20000          0     0.0   1.0
2    15668575   26            43000          0     1.0   0.0
3    15603246   27            57000          0     1.0   0.0
4    15804002   19            76000          0     0.0   1.0
..        ...  ...              ...        ...     ...   ...
395  15691863   46            41000          1     1.0   0.0
396  15706071   51            23000          1     0.0   1.0
397  15654296   50            20000          1     1.0   0.0
398  15755018   36            33000          0     0.0   1.0
399  15594041   49            36000          1     1.0   0.0

[400 rows x 6 columns]

In [6]:
#Extracting Independent and dependent Variable  

x = data.loc[:,['Female','Male','Age','EstimatedSalary']].values
y = data.loc[:,'Purchased'].values.reshape(-1,1)

In [7]:
# Feature scaling 
from sklearn.preprocessing import StandardScaler

scale=StandardScaler()
scaled_x=scale.fit_transform(x[:,[2,3]])

x[:,[2,3]]=scaled_x
x

array([[ 0.        ,  1.        , -1.78179743, -1.49004624],
       [ 0.        ,  1.        , -0.25358736, -1.46068138],
       [ 1.        ,  0.        , -1.11320552, -0.78528968],
       ...,
       [ 1.        ,  0.        ,  1.17910958, -1.46068138],
       [ 0.        ,  1.        , -0.15807423, -1.07893824],
       [ 1.        ,  0.        ,  1.08359645, -0.99084367]])

In [8]:
from IPython.display import display
from sklearn.model_selection import train_test_split

x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

- Fitting Logistic Regression to the Training set

In [9]:
from sklearn.linear_model import LogisticRegression 

logistic_regression=LogisticRegression()
logistic_regression.fit(x_train,y_train)



c:\Users\yunud\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

-  Predicting the Test Result

In [10]:
y_pred=logistic_regression.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

- Test Accuracy of the result

In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm= confusion_matrix(y_test,y_pred) 
print(cm)
print(f"accuracy is {accuracy_score(y_pred=y_pred,y_true=y_test)}")

[[61  2]
 [10 27]]
accuracy is 0.88
